### PR TITLE
PR to merge Milestone 3 into development

### PR DESCRIPTION
**Pull request by talhawaqar**
In this PR functionality of add book and remove book is achieved

### CODE REVIEW

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUIRED🛑️🛑️🛑️**

Hello @talhawaqar 
Great work on this project. You have managed to make most of the requirements. Very impressive👏️👏️

However, let's make small changes and get it approved.

[REQUIRED]: In the bookform.js, there should be a handle change function, making changes to the state, instead of having separate onTitleChange and OnCategorySelectChange.

[REQUIRED]: The booklist component should implement the handleremovebook function and pass it as a prop to the book component, not receive it as a prop.

Make the requested changes and ask for a review👍️👍️

Happy coding💻️💻️💻️💻️

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hello @talhawaqar  👋

**You've done pretty well here fixing a few issues raised in the previous review. 👌**

However, let's make a couple of changes.

- [ ] REQUIRED - Kindly ensure you add the eslintrc.json config as shown in this [link](https://github.com/microverseinc/linters-config/tree/master/react-redux), as it is shared by other students and improves the professionalism of the project.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Comment by talhawaqar** [comment]
> * [ ]  REQUIRED - Kindly ensure you add the eslintrc.json config as shown in this [link](https://github.com/microverseinc/linters-config/blob/master/javascript/.eslintrc.json), as it is shared by other students and improves the professionalism of the project.

It is not compulsory to add the eslitric.json file I set up for GitHub actions for this project and all checks are passed. Moreover, the eslintric.json file you provided is not for React.

**Comment by mikenath223** [comment]
### STATUS: INVALID PR ❌

This PR has been marked as invalid.

Reason: 
- Please ensure you follow [these instructions](https://github.com/microverseinc/linters-config/tree/master/react-redux) and add all files listed there.

Feel free to contact me on slack(@michgolden) if you need further clarifications.

**Comment by talhawaqar** [comment]
> * these instructions

Why you marked pr is invalid. I followed the instructions I set up Github actions.
It takes a second to add the eslintric.json file but the point is why I add this file when I set up GitHub actions.

**Comment by mikenath223** [comment]
Kindly follow the instructions listed there as they are shared by other students. If you disagree with any guideline consider raising a PR to change it.

**Comment by talhawaqar** [comment]
> Kindly follow the instructions listed there as they are shared by other students. If you disagree with any guideline consider raising a PR to change it.

I do not disagree with any requirement but please show me where it is written that it is compulsory to set up linters for your local environment and Github actions for the same time.

**Comment by talhawaqar** [comment]
> > Kindly follow the instructions listed there as they are shared by other students. If you disagree with any guideline consider raising a PR to change it.
> 
> I do not disagree with any requirement but please show me where it is written that it is compulsory to set up linters for your local environment and Github actions for the same time.

Moreover, I am going to add it just for the approval of the project but it does not make sense to do both thins setup linters and Github actions at the same time. Maybe I am wrong but it looks like it is your personal opinion not microverse requirements

**Comment by mikenath223** [comment]
> > > Kindly follow the instructions listed there as they are shared by other students. If you disagree with any guideline consider raising a PR to change it.
> > 
> > 
> > I do not disagree with any requirement but please show me where it is written that it is compulsory to set up linters for your local environment and Github actions for the same time.
> 
> Moreover, I am going to add it just for the approval of the project but it does not make sense to do both thins setup linters and Github actions at the same time. Maybe I am wrong but it looks like it is your personal opinion not microverse requirements

**Kindly note that all requirements for linters are hard requirements.**

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Pull request merged**
